version: "3.6"

services:
  postgres-demo-instance:
    image: postgres:latest
    container_name: postgres-demo-instance
    restart: always
    volumes:
      - postgres_demo_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
volumes:
  postgres_demo_volume: